var GAME_LEVELS = [
  ["                                              y                              x  ",
   "                                                                             x  ",
   "        y                                                                    x  ",
   "                                           o                                 x  ",
   "                            y                                      o         x  ",
   "                                                                             x  ",
   "                                                          xxx     xxx        x  ",
   "                                                  xxx            xx!xx       x  ",
   " y                                                               x!!!x       x  ",
   "                                    o o   xxxx                   xx!xx       x  ",
   "                                                                  xvx        x  ",
   "                                   xxxxx                   y                 x  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                            o  x  ",
   "  x  r       xxxx       o                                z                   x  ",
   "  x  @       x  x                                                xxxxxx      x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx   xxx  xxxxx    xxxxxxxx  ",
   "                              x   x                 x        x                  ",
   "        y                     x!!!x                 x!!!!!!!!x                  ",
   "                              x!!!x         y       x!!!!!!!!x                  ",
   "                              xxxxx                 xxxxxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  [" x                            y                x ",
   " x                                             x ",
   " x                                             x ",
   " x                    o                        x ",
   " x     y              o                        x ",
   " x        r        xxxxx                       x ",
   " x        @                            y       x ",
   " x      xxxxxxx                                x ",
   " x                                             x ",
   " x                 y      o                    x ",
   " x                        o                    x ",
   " x       y                                     x ",
   " x                       xxx                   x ",
   " x                                             x ",
   " x                    o                        x ",
   " x                    o                   z    x ",
   " x                                             x ",
   " x                xxxxxxxxx    xx     xxxxx    x ",
   " x                        x!!!!!!!!!!!x        x ",
   " x                        xxxxxxxxxxxxx        x ",
   " x                                             x ",
   " x                                      y      x ",
   " x                    =                        x ",
   " x  y                                          x ",
   " x                                             x ",
   " x                                   =         x ",
   " x                                             x ",
   " x       o                            o        x ",
   " xxxxxxxxxxxxxxxxxxxx!!!!xxx!!!!xxxxxxxxxxxxxxxx ",
   "                    xxxxxxxxxxxxx                ",
   "                                                 "],
  ["  x                                                                       xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  x                                                y                       xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  x                                                                         xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  x                                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxvxxx  ",
   "  xo                      o                                                                                x  ",
   "  x          y                                                                                             x  ",
   "  x                       o                         o                          o                           x  ",
   "  xxx                                                                                                      x  ",
   "  xo         xxxxxxxxxxxxxxxxxxxxxxgggggxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x  ",
   "  x                                                                                                        x  ",
   "  x                                                               y                                        x  ",
   "  x                                                                                                        x  ",
   "  xxx          y                                                                                       o   x  ",
   "  x                            o o                                                           y             x  ",
   "  x                                                                                     o             xxx  x  ",
   "  x!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 o       x  ",
   "  xxxxxxxxxxvxx                                                                        xxx                 x  ",
   "  x                       y                                                                   o   xxx      x  ",
   "  x      o                                                                                                 x  ",
   "  x                                                         y                                xxx           x  ",
   "  x      o                                                                                                 x  ",
   "  x              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxgggggxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!x  ",
   "  x                                                                                        xxxxxxxxxxxxxxxxx  ",
   "  x                                             y                                                          x  ",
   "  x                                                                                         y              x  ",
   "  x    xxxx                                                             o o                                x  ",
   "  x            y                                                                                    r      x  ",
   "  x                                 z                                                               @      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                              x!!!!!!!!!!!x                           x!!!!!x                                 ",
   "                              xxxxxxxxxxxxx                           xxxxxxx                                 "],
  ["                    v            v                                                                            ",
   "                                               y                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  y           o           o o                                                                                 ",
   "                                                          o                              y                    ",
   "            xxxxx        xxxxx        o                                                                       ",
   "                                                         xxx      xxx                                   y     ",
   "                                     xxx                  v        v                       o                  ",
   "      o                                        xxxx                        xxx                                ",
   "                                                    y                                     xxx                 ",
   "                                                                                                              ",
   "  xxxggggxxxx                                                                       o        y                ",
   "  !         ! o xxxxxxxxx o xxxxxxxxx o xxx                    y                                              ",
   "  !         !   !       !   !       !   !                                          xxx                    o   ",
   "  !         xxxxx       xxxxx       xxxxx                                                                     ",
   "  !                                                                                            o o            ",
   "  !               y                                                               o o                   xxxx  ",
   "  ! r                                          y                                              xxxxx           ",
   "  ! @                                                                     z     xxxxxxx                       ",
   "  xxxxxxx            o  o              xxxxxxxxxxxx  xx    xxx    xx     xxx                          y       ",
   "        x                   =          x          x                      xxx                                  ",
   "        xxx      xxxxxxxxxxxxxx      xxx    y     x!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "  y      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                        "],
  ["                                                                  ",
   "            y                                                     ",
   "                                                                  ",
   "                                      y                           ",
   "                                                                  ",
   "    x    x    xxxx    x    x       x       x   xxxxx   xx    x    ",
   "     x  x    x    x   x    x       x       x     x     x x   x    ",
   "      xx     x    x   x    x  y     x  x  x      x     x  x  x    ",
   "      xx     x    x   x    x        x x x x      x     x   x x    ",
   " x    xx      xxxx     xxxx          x   x     xxxxx   x    xx  x ",
   " x                                                              x ",
   " x                                                              x ",
   " x                                                              x ",
   " x   @                                                          x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "        y                                                 y       "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
